# Generated by Django 3.2.3 on 2021-05-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineBot', '0002_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operation_status',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
