# Generated by Django 3.2.3 on 2021-05-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineBot', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='line_user_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='operation_status',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
