# Generated by Django 3.2.3 on 2021-06-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LineBot', '0006_auto_20210526_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='link',
            new_name='maps_link',
        ),
    ]
