# Generated by Django 3.2.3 on 2021-06-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineBot', '0007_rename_link_location_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='official_website_link',
            field=models.URLField(default='None'),
        ),
    ]
