# Generated by Django 3.2.3 on 2021-06-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineBot', '0008_location_official_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='maps_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='official_website_link',
            field=models.URLField(default=''),
        ),
    ]
