# Generated by Django 3.2.3 on 2021-06-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LineBot', '0009_auto_20210606_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Announcement',
        ),
    ]
